version: "3"

services:
    host1:
        build:
            context: "./"
            dockerfile: "Dockerfile-host.custom"
        container_name: host1
        tty: true
        cap_add:
            - "ALL"
        networks:
            net-a:
                ipv4_address: 192.169.0.2
        command: bash -c "route add -net 192.0.0.0 netmask 255.0.0.0 gw 192.169.0.3 dev eth0 && /bin/bash"

    host2:
        build:
            context: "./"
            dockerfile: "Dockerfile-host.custom"
        container_name: host2
        tty: true
        cap_add:
            - ALL
        networks:
            net-b:
                ipv4_address: 192.168.0.2
        command: bash -c "route add -net 192.0.0.0 netmask 255.0.0.0 gw 192.168.0.3 dev eth0 && /bin/bash"

    router:
        build:
            context: "./"
            dockerfile: "Dockerfile-router.custom"
        container_name: router
        tty: true
        cap_add:
            - ALL
        networks:
            net-a:
                ipv4_address: 192.169.0.3
            net-b:
                ipv4_address: 192.168.0.3
        command: bash -c "sysctl -w net.ipv4.ip_forward=1 && sysctl -p /etc/sysctl.conf && /bin/bash"

networks:
    net-a:
        name: net-a
        driver: bridge
        ipam:
            config:
                - subnet: 192.169.0.0/24
    net-b:
        name: net-b
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.0.0/24

    

