version: "3"

services:
  client:
    build:
      context: "./"
      dockerfile: "Dockerfile-host.custom"
    container_name: client
    hostname: client
    tty: true
    cap_add:
      - "ALL"
    networks:
      net-a:
        ipv4_address: 192.169.1.11
    command: bash -c "route add -net 192.169.0.0 netmask 255.255.0.0 gw 192.169.1.2 dev eth0 && /bin/bash"

  server:
    build:
      context: "./"
      dockerfile: "Dockerfile-host.custom"
    container_name: server
    hostname: server
    tty: true
    cap_add:
      - ALL
    networks:
      net-b:
        ipv4_address: 192.169.2.22
    command: bash -c "route add -net 192.169.0.0 netmask 255.255.0.0 gw 192.169.2.2 dev eth0 && /bin/bash"

  router:
    build:
      context: "./"
      dockerfile: "Dockerfile-router.custom"
    container_name: router
    hostname: router
    tty: true
    cap_add:
      - ALL
    networks:
      net-a:
        ipv4_address: 192.169.1.2
      net-b:
        ipv4_address: 192.169.2.2
    command: bash -c "sysctl -w net.ipv4.ip_forward=1 && sysctl -p /etc/sysctl.conf && /bin/bash"

networks:
  net-a:
    name: net-a
    driver: bridge
    ipam:
      config:
        - subnet: 192.169.1.0/24
  net-b:
    name: net-b
    driver: bridge
    ipam:
      config:
        - subnet: 192.169.2.0/24
